version: '3.4'
services:
  swoft:
    image: swoft/swoft
#    for local develop
#    command: php -S 127.0.0.1:13300
    container_name: user-srv
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    ports:
      - "18500:18500"
      - "18501:18501"
      - "18502:18502"
    volumes:
       - ../:/var/www/
#       - ./:/var/www/swoft:delegated
#      - ./:/var/www/swoft:cached
      # - ./runtime/ng-conf:/etc/nginx
      # - ./runtime/logs:/var/log
    stdin_open: true
    tty: true
    command: /bin/bash
